/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ColecaoEstacaoRouteImport } from './routes/colecao.$estacao'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColecaoEstacaoRoute = ColecaoEstacaoRouteImport.update({
  id: '/colecao/$estacao',
  path: '/colecao/$estacao',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/colecao/$estacao': typeof ColecaoEstacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/colecao/$estacao': typeof ColecaoEstacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/colecao/$estacao': typeof ColecaoEstacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/colecao/$estacao'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/colecao/$estacao'
  id: '__root__' | '/' | '/colecao/$estacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ColecaoEstacaoRoute: typeof ColecaoEstacaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colecao/$estacao': {
      id: '/colecao/$estacao'
      path: '/colecao/$estacao'
      fullPath: '/colecao/$estacao'
      preLoaderRoute: typeof ColecaoEstacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ColecaoEstacaoRoute: ColecaoEstacaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
